---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dotnet-webapp
  template:
    metadata:
      labels:
        app: dotnet-webapp
    spec:
      containers:
      - name: dotnet-webapp-container
        image: testprojectcicd-myimage:62
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapp-svc
spec:
  type: NodePort
  selector:
    app: dotnet-webapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32003
