---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-container
        image: testprojectcicd.azurecr.io/(ACRrepositoryName):63
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-svc
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32003
